"use client";
import {useEffect,useState} from "react";

export default function ResetPassword(){
 const [password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[token,setToken]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const h=new URLSearchParams(window.location.hash.replace(/^#/,""));const q=new URLSearchParams(window.location.search);setToken(h.get("access_token")||q.get("access_token")||"")},[]);
 const save=async()=>{setError("");setMessage("");if(password.length<8)return setError("Le mot de passe doit contenir au moins 8 caractères.");if(password!==confirm)return setError("Les deux mots de passe ne correspondent pas.");if(!token)return setError("Ce lien de réinitialisation est invalide ou a expiré. Demandez un nouveau lien depuis la page de connexion.");setBusy(true);try{const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)throw new Error("Configuration publique Supabase manquante");const r=await fetch(`${url}/auth/v1/user`,{method:"PUT",headers:{apikey:key,Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({password})});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.msg||j.message||"Lien invalide ou expiré")};setMessage("Votre mot de passe a bien été modifié. Vous pouvez maintenant vous connecter.");setPassword("");setConfirm("")}catch(e){setError(e.message||"Modification impossible")}finally{setBusy(false)}};
 return <main className="reset-page"><section className="reset-card"><div className="reset-brand"><span>G</span><div><small>GHR RÉGION SUD</small><strong>Relation adhérents</strong></div></div><p className="eyebrow gold">Sécurité du compte</p><h1>Nouveau mot de passe</h1><p className="meta">Choisissez un nouveau mot de passe pour votre compte individuel GHR.</p><label className="field"><span>Nouveau mot de passe</span><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label><label className="field"><span>Confirmer le mot de passe</span><input className="input" type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password"/></label>{error&&<p className="error auth-error">{error}</p>}{message&&<p className="auth-success">{message}</p>}<button className="btn primary reset-btn" disabled={busy||!!message} onClick={save}>{busy?"Modification…":"Enregistrer le nouveau mot de passe"}</button><a className="auth-link reset-back" href="/">Retour à la connexion</a></section></main>
}
