import {NextResponse} from "next/server";
import {effectiveDelegateId} from "../../../lib/authz";
import {rest} from "../../../lib/supabase";
export const dynamic="force-dynamic";

async function fullState(){const r=await rest("app_state?id=eq.main&select=payload,updated_at");if(!r.ok)throw new Error(await r.text());const rows=await r.json();return{state:rows?.[0]?.payload||{},updatedAt:rows?.[0]?.updated_at||null}}
async function delegates(state){const r=await rest("app_users?role=eq.delegate&select=id,name,email,sector,active,access_ids&order=name.asc");const linked=r.ok?(await r.json()).map(x=>({id:x.id,name:x.name,email:x.email,sector:x.sector||"",active:x.active!==false,accessIds:x.access_ids||[],authLinked:true})):[];const ids=new Set(linked.map(x=>x.id));const legacy=(state.members||[]).filter(x=>!ids.has(x.id)).map(x=>({id:x.id,name:x.name,email:x.email||"",sector:x.sector||"",active:true,accessIds:[],authLinked:false}));return [...linked,...legacy]}
function scopedState(state,delegateId,profiles){const base={...state,members:profiles};if(!delegateId)return base;return{...base,members:profiles.filter(m=>m.id===delegateId),companies:(state.companies||[]).filter(c=>c.ownerId===delegateId),notes:(state.notes||[]).filter(n=>n.target==="all"||n.target===delegateId)}}
export async function GET(){try{const a=await effectiveDelegateId();if(a.error)return NextResponse.json({error:"Authentification requise"},{status:a.status});const {state,updatedAt}=await fullState();const profiles=await delegates(state);return NextResponse.json({state:scopedState(state,a.delegateId,profiles),updatedAt},{headers:{"Cache-Control":"no-store"}})}catch(e){return NextResponse.json({error:e.message||"Erreur de lecture"},{status:500})}}
export async function PUT(req){try{const a=await effectiveDelegateId();if(a.error)return NextResponse.json({error:"Authentification requise"},{status:a.status});const body=await req.json().catch(()=>null);if(!body?.state||typeof body.state!=="object")return NextResponse.json({error:"État invalide"},{status:400});const current=await fullState();let next;if(!a.delegateId&&a.profile.role==="admin"){next={...body.state,members:current.state.members||[]}}else{const delegateId=a.delegateId;const incomingCompanies=(body.state.companies||[]).filter(c=>c.ownerId===delegateId);const otherCompanies=(current.state.companies||[]).filter(c=>c.ownerId!==delegateId);next={...current.state,companies:[...incomingCompanies,...otherCompanies],notes:current.state.notes||[],members:current.state.members||[]}}
 const r=await rest("app_state?on_conflict=id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({id:"main",payload:next,updated_at:new Date().toISOString()})});if(!r.ok)return NextResponse.json({error:await r.text()},{status:500});return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:e.message||"Erreur de sauvegarde"},{status:500})}}
