import {NextResponse} from "next/server";
import {effectiveDelegateId} from "../../../lib/authz";
import {supabaseConfig} from "../../../lib/supabase";
export const dynamic="force-dynamic";const BUCKET="ghr-documents";
function safe(s){return String(s||"document").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]+/g,"-")}
async function allowed(companyId){const a=await effectiveDelegateId();if(a.error)return a;if(!a.delegateId)return{ok:true};const c=supabaseConfig();const r=await fetch(`${c.url}/rest/v1/app_state?id=eq.main&select=payload`,{headers:{apikey:c.key,Authorization:`Bearer ${c.key}`},cache:"no-store"});if(!r.ok)return{error:"state",status:500};const state=(await r.json())?.[0]?.payload||{};const company=(state.companies||[]).find(x=>x.id===companyId);return company?.ownerId===a.delegateId?{ok:true}:{error:"forbidden",status:403}}
export async function POST(req){const form=await req.formData();const file=form.get("file");const companyId=String(form.get("companyId")||"");const membershipId=form.get("membershipId")||"general";const auth=await allowed(companyId);if(!auth.ok)return NextResponse.json({error:"Non autorisé"},{status:auth.status||403});if(!file||typeof file.arrayBuffer!=="function")return NextResponse.json({error:"Fichier manquant"},{status:400});const c=supabaseConfig();const path=`${safe(companyId)}/${safe(membershipId)}/${Date.now()}-${safe(file.name)}`;const r=await fetch(`${c.url}/storage/v1/object/${BUCKET}/${path}`,{method:"POST",headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,"Content-Type":file.type||"application/octet-stream","x-upsert":"false"},body:Buffer.from(await file.arrayBuffer())});if(!r.ok)return NextResponse.json({error:await r.text()},{status:500});return NextResponse.json({path,name:file.name,type:file.type,size:file.size})}
export async function GET(req){const a=await effectiveDelegateId();if(a.error)return new NextResponse("Non autorisé",{status:a.status});const path=new URL(req.url).searchParams.get("path");if(!path)return new NextResponse("Chemin manquant",{status:400});const companyId=path.split("/")[0];const auth=await allowed(companyId);if(!auth.ok)return new NextResponse("Non autorisé",{status:403});const c=supabaseConfig();const r=await fetch(`${c.url}/storage/v1/object/${BUCKET}/${path}`,{headers:{apikey:c.key,Authorization:`Bearer ${c.key}`}});if(!r.ok)return new NextResponse(await r.text(),{status:r.status});return new NextResponse(await r.arrayBuffer(),{headers:{"Content-Type":r.headers.get("content-type")||"application/octet-stream","Content-Disposition":`inline; filename="${safe(path.split("/").pop())}"`}})}
export async function DELETE(req){const a=await effectiveDelegateId();if(a.error)return NextResponse.json({error:"Non autorisé"},{status:a.status});const path=new URL(req.url).searchParams.get("path");if(!path)return NextResponse.json({error:"Chemin manquant"},{status:400});const companyId=path.split("/")[0];const auth=await allowed(companyId);if(!auth.ok)return NextResponse.json({error:"Non autorisé"},{status:403});const c=supabaseConfig();const r=await fetch(`${c.url}/storage/v1/object/${BUCKET}`,{method:"DELETE",headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,"Content-Type":"application/json"},body:JSON.stringify({prefixes:[path]})});if(!r.ok)return NextResponse.json({error:await r.text()},{status:500});return NextResponse.json({ok:true})}
